stages:
  - analyze
  - check
  - build
  - test

sonar-analyze:
  stage: analyze
  image: gradle:7.0.2-jdk16
  tags:
    - kubernetes

  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"

  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/

  script: gradle sonar
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'

build:
  stage: build
  image: cimg/openjdk:16.0.2
  tags:
    - kubernetes
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*
    expire_in: 1 week

test:
  stage: test
  image: cimg/openjdk:16.0.2
  tags:
    - kubernetes
  script:
    - gradle test

check:
  stage: check
  image: cimg/openjdk:16.0.2
  tags:
    - kubernetes
  script:
    - gradle check
  artifacts:
    paths:
      - build/reports/dependency-verification/*
    expire_in: 1 week